f = open("new.txt", "w")
f.write("It is a much easier programming language to learn")
f = open("new.txt", "a")
f.write("\nI will explore the fields of Data Science and Machine Learning")
f.write("\nI will use my learnings in my classes")
f.write("\nI want to become an expert in Data Science and/or Machine Learning")
f = open("new.txt", "r")
print(f.read())
f.close()